### ISSUE TITLE
Breaking change in 1.6.1

### ISSUE THREAD

**Issue by idabmat** [cabbage-ex/gherkin#21]
It looks like a new version of this library was released on hex a little over 1 month ago. Glad to see it gaining a new maintainer.

Unfortunately this new release is causing an issue. #8 was a breaking change and the version was set to `2.0.0` appropriately. But it looks like the version was later changed to `1.6.1` in https://github.com/cabbage-ex/gherkin/commit/3d013c8a708b647af3f81339f70192a8ae5ba33b and then released to hex.

I'm not sure what would be the best approach here. Would it be possible to yank v1.6.1 from hex and re-release it as 2.0.0 instead?

In the mean time the work around for us was to pin `1.6.0` in our mix.exs file.

**Comment by maxmarcon** [comment]
Oh sorry about that and for replying so late! I now realize why the version was set to 2.0.0 in the code. 

I think I can retire 1.6.1 and release 2.0.0.

**Comment by maxmarcon** [comment]
I've retired 1.6.1 and published 2.0.0

I enabled notifications for this repo. I'll be much faster at reacting to issues in the future.

Again, apologies for any inconvenience!
