### ISSUE TITLE
Role for features

### ISSUE THREAD

**Issue by meadsteve** [cabbage-ex/gherkin#9]
Whitebread has some filters that make use of a 'role' for a feature. 

This was removed here: https://github.com/cabbage-ex/gherkin/commit/e8389074de3acb75d7201081deb4dd629c7a36e0#diff-d25be551329fc7c7234e014e4d849b9fL157

Any opposition to adding it back?

**Comment by revati** [comment]
Yeah, if it is in gherkin/cucumber documentation than 100% yes. Otherwise, roles still seem like a very handy tool and will be implemented after 1.0 release (wonder when that will be as least weeks being sick and having much work to do beside this library).

**Comment by meadsteve** [comment]
@revati I'm not sure it's actually part of the gherkin spec but it is useful. Given that the removal of role is a breaking change I'd say it's important to mark the library as 2.0 before the current master gets released

**Comment by meadsteve** [comment]
Which I see has already been done 👍 So nevermind.

This will be a breaking change for whitebread so I'm happy to attempt to re-implent roles in gherkin (once things are stable in 2.0).
